sudo: required

language: scala

scala:
  - 2.11.11
  - 2.12.8

jdk:
  - oraclejdk8

dist: precise

script: 
  - sbt ++$TRAVIS_SCALA_VERSION testAll
  - sbt coverage buildCoverage

after_success:
  - sbt 'project typequuxJVM' coveralls